update

diff --git a/snip b/snip
--- a/snip
+++ b/snip
@@ -21,10 +21,38 @@ dest_file_ext=.png
 
 tmp_dir=/tmp
 
+# outputs full destination path
+join_dest_path () {
+  echo "$dest_path/$dest_filename$dest_file_ext"
+}
+
 notification_title="Screenshot taken"
-notification_body="Saved to '$dest_path/$dest_filename$dest_file_ext'"
+notification_body="Saved to '$(join_dest_path)'"
 notification_id=5445
 notification_timeout=5000
+
+# image file formats
+declare -A img_fmt_ext=(
+  [png]=.png
+)
+
+# video file formats
+declare -A vid_fmt_ext=(
+  [mkv]=.mkv
+  [mp4]=.mp4
+)
+
+throw_error () {
+  case "$1" in
+    codec)
+      echo "error: unable to find $file_format extension for $cmd command"
+      exit 1
+      ;;
+    *)
+      echo "unknown error: exiting"
+      exit 255
+  esac
+}
 
 usage () {
 cat<<EOF
@@ -41,6 +69,7 @@ command:
 options:
   -w|--window           capture active window only (currently only for screenshots)
   -e|--execute [cmd]    command to execute after capture
+  -f|--format [codec]   specify output file format (see available formats below)
   -i|--nid [id]         notification id
   -t|--ntimeout [time]  notification timeout
   -T|--ntitle [title]   notification title
@@ -49,6 +78,10 @@ options:
   -v|--verbose          show notifications and output more stuff ${verbose:+(default)}
 
 any other option is passed as is to the utility used for each task (scrot for screenshot, ffcast for clipboard or ffmpeg for record)
+
+file formats:
+  screenshot  $(for fmt in "${!img_fmt_ext[@]}"; do printf "%s " "$fmt"; done)
+  record      $(for fmt in "${!vid_fmt_ext[@]}"; do printf "%s " "$fmt"; done)
 
 environment variables:
   SNIP_PATH   default destination path for snip (default: $dest_path)
@@ -76,7 +109,10 @@ while [ -n "$1" ]; do
     -e|--execute)
       # command to execute after capture
       post_capture_cmd="$2"
-      e_flag_passed=true
+      shift 2
+      ;;
+    -f|--format)
+      file_format="$2"
       shift 2
       ;;
     -i|--nid)
@@ -119,6 +155,30 @@ if [ ! -e "$dest_path" ]; then
   mkdir -p "$dest_path"
 fi
 
+# set file extension for given format
+case "$cmd" in
+  help)
+    ;;
+  record)
+    new_vid_ext="${vid_fmt_ext[file_format]}"
+    
+    if [ -n "$new_vid_ext" ]; then
+      dest_file_ext="$new_vid_ext"
+    else
+      throw_error codec
+    fi
+    ;;
+  screenshot|clipboard|*)
+    new_img_ext="${img_fmt_ext[file_format]}"
+
+    if [ -n "$new_img_ext" ]; then
+      dest_file_ext="$new_img_ext"
+    else
+      throw_error codec
+    fi
+  ;;
+esac
+
 # wait for set delay before capture
 sleep "$capture_delay"
 
@@ -130,7 +190,7 @@ case "$cmd" in
   clipboard)
     # save image inside /tmp and to clipboard
     dest_path="$tmp_dir"
-    scrot $params "$dest_path/$dest_filename$dest_file_ext" -e 'xclip -selection clipboard -t image/png -i \"$f\"'
+    scrot $params "$(join_dest_path)" -e 'xclip -selection clipboard -t image/png -i \"$f\"'
     ;;
   record)
     if [ "$dest_path" = "$SNIP_PATH" ]; then
@@ -140,13 +200,20 @@ case "$cmd" in
     dest_filename="${dest_filename//\$wx\$h/$screen_res}"
     dest_file_ext=.mkv
 
-    ffmpeg -f x11grab -video_size "$screen_res" -framerate 25 -i "$DISPLAY" -c:v ffvhuff "$dest_path/$dest_filename$dest_file_ext"
+    case "$file_format" in
+      mkv)
+        ffmpeg -f x11grab -video_size "$screen_res" -framerate 25 -i "$DISPLAY" -c:v ffvhuff "$(join_dest_path)"
+        ;;
+      mp4|*)
+        ffmpeg -f x11grab -video_size "$screen_res" -framerate 25 -i "$DISPLAY" -f alsa -i default -c:v libx264 -preset ultrafast -c:a aac "$(join_dest_path)"
+        ;;
+    esac
     ;;
   screenshot|*)
     # take screenshot
     if [ -n "$fullscreen" ]; then
       # fullscreen capture
-      scrot $params "$dest_path/$dest_filename$dest_file_ext"
+      scrot $params "$(join_dest_path)"
     else
       # active window only
       dest="${dest//\$wx\$h/win}"
@@ -155,7 +222,7 @@ case "$cmd" in
     ;;
 esac
 
-post_capture_cmd="${post_capture_cmd//%DEST%]/$dest_path\/$dest_filename$dest_file_ext}"
+post_capture_cmd="${post_capture_cmd//%DEST%/$(join_dest_path)}"
 eval "$post_capture_cmd"
 
 if [ -n "$verbose" ]; then
